DROP TABLE HIBERNATE.T_CAR_SINGLE_TABLE_STRATEGY;
DROP SEQUENCE HIBERNATE.CAR_SEQ;

CREATE TABLE HIBERNATE.T_CAR_SINGLE_TABLE_STRATEGY (
  ID								    NUMBER(19),
  CLASS_NAME_DISCRIMINATOR			    VARCHAR2(100 CHAR),
  NAME								    VARCHAR2(100 CHAR),
  PART_NAME					    VARCHAR2(100 CHAR),
  PART_SIZE								    NUMBER(19),
  PART_WEIGHT							    NUMBER(19),
  DATE_ID							    VARCHAR2(100 CHAR),
  CONSTRAINT PK_CAR PRIMARY KEY (ID)
);

CREATE SEQUENCE HIBERNATE.CAR_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
