DROP TABLE HIBERNATE.T_USER2QUESTION_ANSWER;
DROP TABLE HIBERNATE.T_USERS;
DROP TABLE HIBERNATE.T_QUESTIONS;
DROP SEQUENCE HIBERNATE.USERS_SEQ;
DROP SEQUENCE HIBERNATE.QUESTIONS_SEQ;
DROP SEQUENCE USER_2_QUESTION_SEQ;

CREATE TABLE HIBERNATE.T_USERS (
  ID								NUMBER(19),
  NAME								VARCHAR2(100 CHAR),
  SURNAME							VARCHAR2(100 CHAR),
  DATE_ID							VARCHAR2(100 CHAR),
  CONSTRAINT PK_USER PRIMARY KEY (ID)
);

CREATE TABLE HIBERNATE.T_QUESTIONS (
  ID								NUMBER(19),
  QUERY								VARCHAR2(100 CHAR),
  DATE_ID							VARCHAR2(100 CHAR),
  CONSTRAINT PK_QUESTION PRIMARY KEY (ID)
);

CREATE TABLE HIBERNATE.T_USER2QUESTION_ANSWER (
  ID								NUMBER(19),
  ID_USER							NUMBER(19),
  ID_QUESTION						NUMBER(19),
  ACCEPTED							VARCHAR2(1 CHAR),
  CONSTRAINT PK_USER2QUESTION PRIMARY KEY (ID),
  CONSTRAINT FK_U2Q_USERS FOREIGN KEY (ID_USER) REFERENCES T_USERS(ID),
  CONSTRAINT FK_U2Q_QUESTIONS FOREIGN KEY (ID_QUESTION) REFERENCES T_QUESTIONS(ID)
);

CREATE SEQUENCE HIBERNATE.USERS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE HIBERNATE.QUESTIONS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE HIBERNATE.USER_2_QUESTION_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
