DROP TABLE HIBERNATE.T_USERS;
DROP TABLE HIBERNATE.T_USER_DETAILS;
DROP SEQUENCE HIBERNATE.USERS_SEQ;

CREATE TABLE HIBERNATE.T_USER_DETAILS (
  ID								NUMBER(15),
  DETAILS							VARCHAR2(100 CHAR) NOT NULL,
  CONSTRAINT UDETAILS_PK PRIMARY KEY (ID)
);

CREATE TABLE HIBERNATE.T_USERS (
  ID								NUMBER(15),
  ID_USER_DETAILS					NUMBER(15) NOT NULL,
  NAME								VARCHAR2(100 CHAR),
  CONSTRAINT USER_PK PRIMARY KEY (ID),
  CONSTRAINT UDETAILS_UK UNIQUE (ID_USER_DETAILS),
  CONSTRAINT UDETAILS_FK FOREIGN KEY (ID_USER_DETAILS) REFERENCES T_USER_DETAILS(ID)
);

CREATE SEQUENCE HIBERNATE.USERS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
