DROP TABLE HIBERNATE.T_ORDER2PRODUCT;
DROP TABLE HIBERNATE.T_ORDERS;
DROP TABLE HIBERNATE.T_PRODUCTS;
DROP SEQUENCE HIBERNATE.ORDERS_SEQ;
DROP SEQUENCE HIBERNATE.PRODUCTS_SEQ;

CREATE TABLE HIBERNATE.T_PRODUCTS (
  ID								NUMBER(19),
  NAME								VARCHAR2(100 CHAR),
  CONSTRAINT PK_PRODUCT PRIMARY KEY (ID)
);

CREATE TABLE HIBERNATE.T_ORDERS (
  ID								NUMBER(19),
  ORDER_DETAILS						VARCHAR2(100 CHAR),
  CONSTRAINT PK_ORDER PRIMARY KEY (ID)
);

CREATE TABLE HIBERNATE.T_ORDER2PRODUCT (
  ID_ORDER							NUMBER(19),
  ID_PRODUCT						NUMBER(19),
  CONSTRAINT FK_O2P_ORDERS FOREIGN KEY (ID_ORDER) REFERENCES T_ORDERS(ID),
  CONSTRAINT FK_O2P_PRODUCTS FOREIGN KEY (ID_PRODUCT) REFERENCES T_PRODUCTS(ID)
);

CREATE SEQUENCE HIBERNATE.PRODUCTS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE HIBERNATE.ORDERS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
