-- ON ROOT
DROP DATABASE HIBERNATE;
DROP USER 'HIBERNATE'@'LOCALHOST';

CREATE DATABASE HIBERNATE;
CREATE USER 'HIBERNATE'@'LOCALHOST' IDENTIFIED BY 'HIBERNATE' PASSWORD EXPIRE NEVER;
GRANT ALL ON HIBERNATE.* TO 'HIBERNATE'@'LOCALHOST';
