DROP TABLE HIBERNATE.T_CAR;

CREATE TABLE HIBERNATE.T_CAR (
   ID 				INT NOT NULL AUTO_INCREMENT,
   NAME 			VARCHAR(100) NOT NULL,
   DATE_ID 			VARCHAR(100) NOT NULL,
   PRIMARY KEY ( ID )
);